name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
    - name: Enable nix-command feature
      run: echo "experimental-features = nix-command" | sudo tee -a /etc/nix/nix.conf
    - uses: cachix/cachix-action@v6
      with:
        name: pbogdan
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Nix Stable build
      run: nix-build
    - name: Enable flake support
      run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
    - name: Nix Flakes build
      run: nix build
