name: Update flake inputs

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  release:
    name: Update flake inputs
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
      - name: Update flake inputs
        uses: technote-space/create-pr-action@v2.0.29
        with:
          EXECUTE_COMMANDS: |
            echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
            nix flake update --recreate-lock-file
          COMMIT_MESSAGE: "flake: update inputs"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "noreply@github.com"
          PR_BRANCH_NAME: "flake-update-inputs-${PR_ID}"
          PR_TITLE: "flake: update inputs"
